<?php


/**
 * This class adds structure of 'noticia' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Tue Nov 10 21:52:53 2009
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class NoticiaMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.NoticiaMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(NoticiaPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(NoticiaPeer::TABLE_NAME);
		$tMap->setPhpName('Noticia');
		$tMap->setClassname('Noticia');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

		$tMap->addForeignKey('EMPRESA_ID', 'EmpresaId', 'INTEGER', 'empresa', 'ID', true, null);

		$tMap->addColumn('TITULO', 'Titulo', 'VARCHAR', true, 150);

		$tMap->addColumn('TEXTO', 'Texto', 'LONGVARCHAR', false, null);

		$tMap->addColumn('FECHA_PUBLICACION', 'FechaPublicacion', 'DATE', false, null);

		$tMap->addColumn('FECHA_CANCELACION', 'FechaCancelacion', 'DATE', false, null);

		$tMap->addColumn('SLOT', 'Slot', 'VARCHAR', false, 150);

	} // doBuild()

} // NoticiaMapBuilder
