<?php


/**
 * This class adds structure of 'ubicacion' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Tue Nov 10 21:52:53 2009
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class UbicacionMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.UbicacionMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(UbicacionPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(UbicacionPeer::TABLE_NAME);
		$tMap->setPhpName('Ubicacion');
		$tMap->setClassname('Ubicacion');

		$tMap->setUseIdGenerator(false);

		$tMap->addForeignPrimaryKey('EMPRESA_ID', 'EmpresaId', 'INTEGER' , 'empresa', 'ID', true, null);

		$tMap->addColumn('CALLE', 'Calle', 'VARCHAR', false, 200);

		$tMap->addColumn('NUMERO', 'Numero', 'INTEGER', false, null);

		$tMap->addColumn('COLONIA', 'Colonia', 'VARCHAR', true, 200);

		$tMap->addColumn('CODIGO_POSTAL', 'CodigoPostal', 'INTEGER', true, null);

		$tMap->addColumn('DELEGACION', 'Delegacion', 'VARCHAR', true, 150);

		$tMap->addForeignKey('ESTADO_ID', 'EstadoId', 'INTEGER', 'estado', 'ID', false, null);

		$tMap->addColumn('LATITUD', 'Latitud', 'DOUBLE', false, null);

		$tMap->addColumn('LONGITUD', 'Longitud', 'DOUBLE', false, null);

		$tMap->addColumn('METRO', 'Metro', 'VARCHAR', false, 100);

	} // doBuild()

} // UbicacionMapBuilder
