<?php


/**
 * This class adds structure of 'visitante' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Tue Nov 10 21:52:53 2009
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class VisitanteMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.VisitanteMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(VisitantePeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(VisitantePeer::TABLE_NAME);
		$tMap->setPhpName('Visitante');
		$tMap->setClassname('Visitante');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

		$tMap->addColumn('USERNAME', 'Username', 'VARCHAR', true, 30);

		$tMap->addColumn('PASSWORD', 'Password', 'VARCHAR', true, 36);

		$tMap->addColumn('EMAIL', 'Email', 'VARCHAR', true, 150);

		$tMap->addColumn('NOMBRE', 'Nombre', 'VARCHAR', false, 50);

		$tMap->addColumn('APELLIDOS', 'Apellidos', 'VARCHAR', false, 100);

		$tMap->addColumn('TARJETA_FONACOT', 'TarjetaFonacot', 'VARCHAR', false, 100);

		$tMap->addColumn('PROMOCION_LIST', 'PromocionList', 'BOOLEAN', false, null);

	} // doBuild()

} // VisitanteMapBuilder
