<?php

/**
 * Base class that represents a row from the 'tramite' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Tue Nov 10 21:52:53 2009
 *
 * @package    lib.model.om
 */
abstract class BaseTramite extends BaseObject  implements Persistent {


  const PEER = 'TramitePeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        TramitePeer
	 */
	protected static $peer;

	/**
	 * The value for the empresa_id field.
	 * @var        int
	 */
	protected $empresa_id;

	/**
	 * The value for the recepcion_del_credito field.
	 * @var        string
	 */
	protected $recepcion_del_credito;

	/**
	 * The value for the recepcion_del_tramite field.
	 * @var        string
	 */
	protected $recepcion_del_tramite;

	/**
	 * The value for the persona_encargada field.
	 * @var        string
	 */
	protected $persona_encargada;

	/**
	 * The value for the horario field.
	 * @var        string
	 */
	protected $horario;

	/**
	 * The value for the procedimiento field.
	 * @var        string
	 */
	protected $procedimiento;

	/**
	 * The value for the documentacion field.
	 * @var        string
	 */
	protected $documentacion;

	/**
	 * @var        Empresa
	 */
	protected $aEmpresa;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseTramite object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
	}

	/**
	 * Get the [empresa_id] column value.
	 * 
	 * @return     int
	 */
	public function getEmpresaId()
	{
		return $this->empresa_id;
	}

	/**
	 * Get the [recepcion_del_credito] column value.
	 * 
	 * @return     string
	 */
	public function getRecepcionDelCredito()
	{
		return $this->recepcion_del_credito;
	}

	/**
	 * Get the [recepcion_del_tramite] column value.
	 * 
	 * @return     string
	 */
	public function getRecepcionDelTramite()
	{
		return $this->recepcion_del_tramite;
	}

	/**
	 * Get the [persona_encargada] column value.
	 * 
	 * @return     string
	 */
	public function getPersonaEncargada()
	{
		return $this->persona_encargada;
	}

	/**
	 * Get the [horario] column value.
	 * 
	 * @return     string
	 */
	public function getHorario()
	{
		return $this->horario;
	}

	/**
	 * Get the [procedimiento] column value.
	 * 
	 * @return     string
	 */
	public function getProcedimiento()
	{
		return $this->procedimiento;
	}

	/**
	 * Get the [documentacion] column value.
	 * 
	 * @return     string
	 */
	public function getDocumentacion()
	{
		return $this->documentacion;
	}

	/**
	 * Set the value of [empresa_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Tramite The current object (for fluent API support)
	 */
	public function setEmpresaId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->empresa_id !== $v) {
			$this->empresa_id = $v;
			$this->modifiedColumns[] = TramitePeer::EMPRESA_ID;
		}

		if ($this->aEmpresa !== null && $this->aEmpresa->getId() !== $v) {
			$this->aEmpresa = null;
		}

		return $this;
	} // setEmpresaId()

	/**
	 * Set the value of [recepcion_del_credito] column.
	 * 
	 * @param      string $v new value
	 * @return     Tramite The current object (for fluent API support)
	 */
	public function setRecepcionDelCredito($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->recepcion_del_credito !== $v) {
			$this->recepcion_del_credito = $v;
			$this->modifiedColumns[] = TramitePeer::RECEPCION_DEL_CREDITO;
		}

		return $this;
	} // setRecepcionDelCredito()

	/**
	 * Set the value of [recepcion_del_tramite] column.
	 * 
	 * @param      string $v new value
	 * @return     Tramite The current object (for fluent API support)
	 */
	public function setRecepcionDelTramite($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->recepcion_del_tramite !== $v) {
			$this->recepcion_del_tramite = $v;
			$this->modifiedColumns[] = TramitePeer::RECEPCION_DEL_TRAMITE;
		}

		return $this;
	} // setRecepcionDelTramite()

	/**
	 * Set the value of [persona_encargada] column.
	 * 
	 * @param      string $v new value
	 * @return     Tramite The current object (for fluent API support)
	 */
	public function setPersonaEncargada($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->persona_encargada !== $v) {
			$this->persona_encargada = $v;
			$this->modifiedColumns[] = TramitePeer::PERSONA_ENCARGADA;
		}

		return $this;
	} // setPersonaEncargada()

	/**
	 * Set the value of [horario] column.
	 * 
	 * @param      string $v new value
	 * @return     Tramite The current object (for fluent API support)
	 */
	public function setHorario($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->horario !== $v) {
			$this->horario = $v;
			$this->modifiedColumns[] = TramitePeer::HORARIO;
		}

		return $this;
	} // setHorario()

	/**
	 * Set the value of [procedimiento] column.
	 * 
	 * @param      string $v new value
	 * @return     Tramite The current object (for fluent API support)
	 */
	public function setProcedimiento($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->procedimiento !== $v) {
			$this->procedimiento = $v;
			$this->modifiedColumns[] = TramitePeer::PROCEDIMIENTO;
		}

		return $this;
	} // setProcedimiento()

	/**
	 * Set the value of [documentacion] column.
	 * 
	 * @param      string $v new value
	 * @return     Tramite The current object (for fluent API support)
	 */
	public function setDocumentacion($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->documentacion !== $v) {
			$this->documentacion = $v;
			$this->modifiedColumns[] = TramitePeer::DOCUMENTACION;
		}

		return $this;
	} // setDocumentacion()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array())) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->empresa_id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->recepcion_del_credito = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->recepcion_del_tramite = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->persona_encargada = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->horario = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->procedimiento = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->documentacion = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 7; // 7 = TramitePeer::NUM_COLUMNS - TramitePeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Tramite object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aEmpresa !== null && $this->empresa_id !== $this->aEmpresa->getId()) {
			$this->aEmpresa = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(TramitePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = TramitePeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aEmpresa = null;
		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseTramite:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(TramitePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			TramitePeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseTramite:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseTramite:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(TramitePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseTramite:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			TramitePeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aEmpresa !== null) {
				if ($this->aEmpresa->isModified() || $this->aEmpresa->isNew()) {
					$affectedRows += $this->aEmpresa->save($con);
				}
				$this->setEmpresa($this->aEmpresa);
			}


			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = TramitePeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setNew(false);
				} else {
					$affectedRows += TramitePeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aEmpresa !== null) {
				if (!$this->aEmpresa->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aEmpresa->getValidationFailures());
				}
			}


			if (($retval = TramitePeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = TramitePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getEmpresaId();
				break;
			case 1:
				return $this->getRecepcionDelCredito();
				break;
			case 2:
				return $this->getRecepcionDelTramite();
				break;
			case 3:
				return $this->getPersonaEncargada();
				break;
			case 4:
				return $this->getHorario();
				break;
			case 5:
				return $this->getProcedimiento();
				break;
			case 6:
				return $this->getDocumentacion();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = TramitePeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getEmpresaId(),
			$keys[1] => $this->getRecepcionDelCredito(),
			$keys[2] => $this->getRecepcionDelTramite(),
			$keys[3] => $this->getPersonaEncargada(),
			$keys[4] => $this->getHorario(),
			$keys[5] => $this->getProcedimiento(),
			$keys[6] => $this->getDocumentacion(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = TramitePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setEmpresaId($value);
				break;
			case 1:
				$this->setRecepcionDelCredito($value);
				break;
			case 2:
				$this->setRecepcionDelTramite($value);
				break;
			case 3:
				$this->setPersonaEncargada($value);
				break;
			case 4:
				$this->setHorario($value);
				break;
			case 5:
				$this->setProcedimiento($value);
				break;
			case 6:
				$this->setDocumentacion($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = TramitePeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setEmpresaId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setRecepcionDelCredito($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setRecepcionDelTramite($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setPersonaEncargada($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setHorario($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setProcedimiento($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setDocumentacion($arr[$keys[6]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(TramitePeer::DATABASE_NAME);

		if ($this->isColumnModified(TramitePeer::EMPRESA_ID)) $criteria->add(TramitePeer::EMPRESA_ID, $this->empresa_id);
		if ($this->isColumnModified(TramitePeer::RECEPCION_DEL_CREDITO)) $criteria->add(TramitePeer::RECEPCION_DEL_CREDITO, $this->recepcion_del_credito);
		if ($this->isColumnModified(TramitePeer::RECEPCION_DEL_TRAMITE)) $criteria->add(TramitePeer::RECEPCION_DEL_TRAMITE, $this->recepcion_del_tramite);
		if ($this->isColumnModified(TramitePeer::PERSONA_ENCARGADA)) $criteria->add(TramitePeer::PERSONA_ENCARGADA, $this->persona_encargada);
		if ($this->isColumnModified(TramitePeer::HORARIO)) $criteria->add(TramitePeer::HORARIO, $this->horario);
		if ($this->isColumnModified(TramitePeer::PROCEDIMIENTO)) $criteria->add(TramitePeer::PROCEDIMIENTO, $this->procedimiento);
		if ($this->isColumnModified(TramitePeer::DOCUMENTACION)) $criteria->add(TramitePeer::DOCUMENTACION, $this->documentacion);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(TramitePeer::DATABASE_NAME);

		$criteria->add(TramitePeer::EMPRESA_ID, $this->empresa_id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getEmpresaId();
	}

	/**
	 * Generic method to set the primary key (empresa_id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setEmpresaId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Tramite (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setEmpresaId($this->empresa_id);

		$copyObj->setRecepcionDelCredito($this->recepcion_del_credito);

		$copyObj->setRecepcionDelTramite($this->recepcion_del_tramite);

		$copyObj->setPersonaEncargada($this->persona_encargada);

		$copyObj->setHorario($this->horario);

		$copyObj->setProcedimiento($this->procedimiento);

		$copyObj->setDocumentacion($this->documentacion);


		$copyObj->setNew(true);

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Tramite Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     TramitePeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new TramitePeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Empresa object.
	 *
	 * @param      Empresa $v
	 * @return     Tramite The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setEmpresa(Empresa $v = null)
	{
		if ($v === null) {
			$this->setEmpresaId(NULL);
		} else {
			$this->setEmpresaId($v->getId());
		}

		$this->aEmpresa = $v;

		// Add binding for other direction of this 1:1 relationship.
		if ($v !== null) {
			$v->setTramite($this);
		}

		return $this;
	}


	/**
	 * Get the associated Empresa object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Empresa The associated Empresa object.
	 * @throws     PropelException
	 */
	public function getEmpresa(PropelPDO $con = null)
	{
		if ($this->aEmpresa === null && ($this->empresa_id !== null)) {
			$c = new Criteria(EmpresaPeer::DATABASE_NAME);
			$c->add(EmpresaPeer::ID, $this->empresa_id);
			$this->aEmpresa = EmpresaPeer::doSelectOne($c, $con);
			// Because this foreign key represents a one-to-one relationship, we will create a bi-directional association.
			$this->aEmpresa->setTramite($this);
		}
		return $this->aEmpresa;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

			$this->aEmpresa = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseTramite:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseTramite::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseTramite
