<?php

/**
 * Base class that represents a row from the 'ubicacion' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Tue Nov 10 21:52:53 2009
 *
 * @package    lib.model.om
 */
abstract class BaseUbicacion extends BaseObject  implements Persistent {


  const PEER = 'UbicacionPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        UbicacionPeer
	 */
	protected static $peer;

	/**
	 * The value for the empresa_id field.
	 * @var        int
	 */
	protected $empresa_id;

	/**
	 * The value for the calle field.
	 * @var        string
	 */
	protected $calle;

	/**
	 * The value for the numero field.
	 * @var        int
	 */
	protected $numero;

	/**
	 * The value for the colonia field.
	 * @var        string
	 */
	protected $colonia;

	/**
	 * The value for the codigo_postal field.
	 * @var        int
	 */
	protected $codigo_postal;

	/**
	 * The value for the delegacion field.
	 * @var        string
	 */
	protected $delegacion;

	/**
	 * The value for the estado_id field.
	 * @var        int
	 */
	protected $estado_id;

	/**
	 * The value for the latitud field.
	 * @var        double
	 */
	protected $latitud;

	/**
	 * The value for the longitud field.
	 * @var        double
	 */
	protected $longitud;

	/**
	 * The value for the metro field.
	 * @var        string
	 */
	protected $metro;

	/**
	 * @var        Empresa
	 */
	protected $aEmpresa;

	/**
	 * @var        Estado
	 */
	protected $aEstado;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseUbicacion object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
	}

	/**
	 * Get the [empresa_id] column value.
	 * 
	 * @return     int
	 */
	public function getEmpresaId()
	{
		return $this->empresa_id;
	}

	/**
	 * Get the [calle] column value.
	 * 
	 * @return     string
	 */
	public function getCalle()
	{
		return $this->calle;
	}

	/**
	 * Get the [numero] column value.
	 * 
	 * @return     int
	 */
	public function getNumero()
	{
		return $this->numero;
	}

	/**
	 * Get the [colonia] column value.
	 * 
	 * @return     string
	 */
	public function getColonia()
	{
		return $this->colonia;
	}

	/**
	 * Get the [codigo_postal] column value.
	 * 
	 * @return     int
	 */
	public function getCodigoPostal()
	{
		return $this->codigo_postal;
	}

	/**
	 * Get the [delegacion] column value.
	 * 
	 * @return     string
	 */
	public function getDelegacion()
	{
		return $this->delegacion;
	}

	/**
	 * Get the [estado_id] column value.
	 * 
	 * @return     int
	 */
	public function getEstadoId()
	{
		return $this->estado_id;
	}

	/**
	 * Get the [latitud] column value.
	 * 
	 * @return     double
	 */
	public function getLatitud()
	{
		return $this->latitud;
	}

	/**
	 * Get the [longitud] column value.
	 * 
	 * @return     double
	 */
	public function getLongitud()
	{
		return $this->longitud;
	}

	/**
	 * Get the [metro] column value.
	 * 
	 * @return     string
	 */
	public function getMetro()
	{
		return $this->metro;
	}

	/**
	 * Set the value of [empresa_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Ubicacion The current object (for fluent API support)
	 */
	public function setEmpresaId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->empresa_id !== $v) {
			$this->empresa_id = $v;
			$this->modifiedColumns[] = UbicacionPeer::EMPRESA_ID;
		}

		if ($this->aEmpresa !== null && $this->aEmpresa->getId() !== $v) {
			$this->aEmpresa = null;
		}

		return $this;
	} // setEmpresaId()

	/**
	 * Set the value of [calle] column.
	 * 
	 * @param      string $v new value
	 * @return     Ubicacion The current object (for fluent API support)
	 */
	public function setCalle($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->calle !== $v) {
			$this->calle = $v;
			$this->modifiedColumns[] = UbicacionPeer::CALLE;
		}

		return $this;
	} // setCalle()

	/**
	 * Set the value of [numero] column.
	 * 
	 * @param      int $v new value
	 * @return     Ubicacion The current object (for fluent API support)
	 */
	public function setNumero($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->numero !== $v) {
			$this->numero = $v;
			$this->modifiedColumns[] = UbicacionPeer::NUMERO;
		}

		return $this;
	} // setNumero()

	/**
	 * Set the value of [colonia] column.
	 * 
	 * @param      string $v new value
	 * @return     Ubicacion The current object (for fluent API support)
	 */
	public function setColonia($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->colonia !== $v) {
			$this->colonia = $v;
			$this->modifiedColumns[] = UbicacionPeer::COLONIA;
		}

		return $this;
	} // setColonia()

	/**
	 * Set the value of [codigo_postal] column.
	 * 
	 * @param      int $v new value
	 * @return     Ubicacion The current object (for fluent API support)
	 */
	public function setCodigoPostal($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->codigo_postal !== $v) {
			$this->codigo_postal = $v;
			$this->modifiedColumns[] = UbicacionPeer::CODIGO_POSTAL;
		}

		return $this;
	} // setCodigoPostal()

	/**
	 * Set the value of [delegacion] column.
	 * 
	 * @param      string $v new value
	 * @return     Ubicacion The current object (for fluent API support)
	 */
	public function setDelegacion($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->delegacion !== $v) {
			$this->delegacion = $v;
			$this->modifiedColumns[] = UbicacionPeer::DELEGACION;
		}

		return $this;
	} // setDelegacion()

	/**
	 * Set the value of [estado_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Ubicacion The current object (for fluent API support)
	 */
	public function setEstadoId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->estado_id !== $v) {
			$this->estado_id = $v;
			$this->modifiedColumns[] = UbicacionPeer::ESTADO_ID;
		}

		if ($this->aEstado !== null && $this->aEstado->getId() !== $v) {
			$this->aEstado = null;
		}

		return $this;
	} // setEstadoId()

	/**
	 * Set the value of [latitud] column.
	 * 
	 * @param      double $v new value
	 * @return     Ubicacion The current object (for fluent API support)
	 */
	public function setLatitud($v)
	{
		if ($v !== null) {
			$v = (double) $v;
		}

		if ($this->latitud !== $v) {
			$this->latitud = $v;
			$this->modifiedColumns[] = UbicacionPeer::LATITUD;
		}

		return $this;
	} // setLatitud()

	/**
	 * Set the value of [longitud] column.
	 * 
	 * @param      double $v new value
	 * @return     Ubicacion The current object (for fluent API support)
	 */
	public function setLongitud($v)
	{
		if ($v !== null) {
			$v = (double) $v;
		}

		if ($this->longitud !== $v) {
			$this->longitud = $v;
			$this->modifiedColumns[] = UbicacionPeer::LONGITUD;
		}

		return $this;
	} // setLongitud()

	/**
	 * Set the value of [metro] column.
	 * 
	 * @param      string $v new value
	 * @return     Ubicacion The current object (for fluent API support)
	 */
	public function setMetro($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->metro !== $v) {
			$this->metro = $v;
			$this->modifiedColumns[] = UbicacionPeer::METRO;
		}

		return $this;
	} // setMetro()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array())) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->empresa_id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->calle = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->numero = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->colonia = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->codigo_postal = ($row[$startcol + 4] !== null) ? (int) $row[$startcol + 4] : null;
			$this->delegacion = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->estado_id = ($row[$startcol + 6] !== null) ? (int) $row[$startcol + 6] : null;
			$this->latitud = ($row[$startcol + 7] !== null) ? (double) $row[$startcol + 7] : null;
			$this->longitud = ($row[$startcol + 8] !== null) ? (double) $row[$startcol + 8] : null;
			$this->metro = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 10; // 10 = UbicacionPeer::NUM_COLUMNS - UbicacionPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Ubicacion object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aEmpresa !== null && $this->empresa_id !== $this->aEmpresa->getId()) {
			$this->aEmpresa = null;
		}
		if ($this->aEstado !== null && $this->estado_id !== $this->aEstado->getId()) {
			$this->aEstado = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(UbicacionPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = UbicacionPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aEmpresa = null;
			$this->aEstado = null;
		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseUbicacion:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(UbicacionPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			UbicacionPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseUbicacion:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseUbicacion:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(UbicacionPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseUbicacion:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			UbicacionPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aEmpresa !== null) {
				if ($this->aEmpresa->isModified() || $this->aEmpresa->isNew()) {
					$affectedRows += $this->aEmpresa->save($con);
				}
				$this->setEmpresa($this->aEmpresa);
			}

			if ($this->aEstado !== null) {
				if ($this->aEstado->isModified() || $this->aEstado->isNew()) {
					$affectedRows += $this->aEstado->save($con);
				}
				$this->setEstado($this->aEstado);
			}


			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = UbicacionPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setNew(false);
				} else {
					$affectedRows += UbicacionPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aEmpresa !== null) {
				if (!$this->aEmpresa->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aEmpresa->getValidationFailures());
				}
			}

			if ($this->aEstado !== null) {
				if (!$this->aEstado->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aEstado->getValidationFailures());
				}
			}


			if (($retval = UbicacionPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = UbicacionPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getEmpresaId();
				break;
			case 1:
				return $this->getCalle();
				break;
			case 2:
				return $this->getNumero();
				break;
			case 3:
				return $this->getColonia();
				break;
			case 4:
				return $this->getCodigoPostal();
				break;
			case 5:
				return $this->getDelegacion();
				break;
			case 6:
				return $this->getEstadoId();
				break;
			case 7:
				return $this->getLatitud();
				break;
			case 8:
				return $this->getLongitud();
				break;
			case 9:
				return $this->getMetro();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = UbicacionPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getEmpresaId(),
			$keys[1] => $this->getCalle(),
			$keys[2] => $this->getNumero(),
			$keys[3] => $this->getColonia(),
			$keys[4] => $this->getCodigoPostal(),
			$keys[5] => $this->getDelegacion(),
			$keys[6] => $this->getEstadoId(),
			$keys[7] => $this->getLatitud(),
			$keys[8] => $this->getLongitud(),
			$keys[9] => $this->getMetro(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = UbicacionPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setEmpresaId($value);
				break;
			case 1:
				$this->setCalle($value);
				break;
			case 2:
				$this->setNumero($value);
				break;
			case 3:
				$this->setColonia($value);
				break;
			case 4:
				$this->setCodigoPostal($value);
				break;
			case 5:
				$this->setDelegacion($value);
				break;
			case 6:
				$this->setEstadoId($value);
				break;
			case 7:
				$this->setLatitud($value);
				break;
			case 8:
				$this->setLongitud($value);
				break;
			case 9:
				$this->setMetro($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = UbicacionPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setEmpresaId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setCalle($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setNumero($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setColonia($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setCodigoPostal($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setDelegacion($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setEstadoId($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setLatitud($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setLongitud($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setMetro($arr[$keys[9]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(UbicacionPeer::DATABASE_NAME);

		if ($this->isColumnModified(UbicacionPeer::EMPRESA_ID)) $criteria->add(UbicacionPeer::EMPRESA_ID, $this->empresa_id);
		if ($this->isColumnModified(UbicacionPeer::CALLE)) $criteria->add(UbicacionPeer::CALLE, $this->calle);
		if ($this->isColumnModified(UbicacionPeer::NUMERO)) $criteria->add(UbicacionPeer::NUMERO, $this->numero);
		if ($this->isColumnModified(UbicacionPeer::COLONIA)) $criteria->add(UbicacionPeer::COLONIA, $this->colonia);
		if ($this->isColumnModified(UbicacionPeer::CODIGO_POSTAL)) $criteria->add(UbicacionPeer::CODIGO_POSTAL, $this->codigo_postal);
		if ($this->isColumnModified(UbicacionPeer::DELEGACION)) $criteria->add(UbicacionPeer::DELEGACION, $this->delegacion);
		if ($this->isColumnModified(UbicacionPeer::ESTADO_ID)) $criteria->add(UbicacionPeer::ESTADO_ID, $this->estado_id);
		if ($this->isColumnModified(UbicacionPeer::LATITUD)) $criteria->add(UbicacionPeer::LATITUD, $this->latitud);
		if ($this->isColumnModified(UbicacionPeer::LONGITUD)) $criteria->add(UbicacionPeer::LONGITUD, $this->longitud);
		if ($this->isColumnModified(UbicacionPeer::METRO)) $criteria->add(UbicacionPeer::METRO, $this->metro);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(UbicacionPeer::DATABASE_NAME);

		$criteria->add(UbicacionPeer::EMPRESA_ID, $this->empresa_id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getEmpresaId();
	}

	/**
	 * Generic method to set the primary key (empresa_id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setEmpresaId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Ubicacion (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setEmpresaId($this->empresa_id);

		$copyObj->setCalle($this->calle);

		$copyObj->setNumero($this->numero);

		$copyObj->setColonia($this->colonia);

		$copyObj->setCodigoPostal($this->codigo_postal);

		$copyObj->setDelegacion($this->delegacion);

		$copyObj->setEstadoId($this->estado_id);

		$copyObj->setLatitud($this->latitud);

		$copyObj->setLongitud($this->longitud);

		$copyObj->setMetro($this->metro);


		$copyObj->setNew(true);

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Ubicacion Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     UbicacionPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new UbicacionPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Empresa object.
	 *
	 * @param      Empresa $v
	 * @return     Ubicacion The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setEmpresa(Empresa $v = null)
	{
		if ($v === null) {
			$this->setEmpresaId(NULL);
		} else {
			$this->setEmpresaId($v->getId());
		}

		$this->aEmpresa = $v;

		// Add binding for other direction of this 1:1 relationship.
		if ($v !== null) {
			$v->setUbicacion($this);
		}

		return $this;
	}


	/**
	 * Get the associated Empresa object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Empresa The associated Empresa object.
	 * @throws     PropelException
	 */
	public function getEmpresa(PropelPDO $con = null)
	{
		if ($this->aEmpresa === null && ($this->empresa_id !== null)) {
			$c = new Criteria(EmpresaPeer::DATABASE_NAME);
			$c->add(EmpresaPeer::ID, $this->empresa_id);
			$this->aEmpresa = EmpresaPeer::doSelectOne($c, $con);
			// Because this foreign key represents a one-to-one relationship, we will create a bi-directional association.
			$this->aEmpresa->setUbicacion($this);
		}
		return $this->aEmpresa;
	}

	/**
	 * Declares an association between this object and a Estado object.
	 *
	 * @param      Estado $v
	 * @return     Ubicacion The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setEstado(Estado $v = null)
	{
		if ($v === null) {
			$this->setEstadoId(NULL);
		} else {
			$this->setEstadoId($v->getId());
		}

		$this->aEstado = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Estado object, it will not be re-added.
		if ($v !== null) {
			$v->addUbicacion($this);
		}

		return $this;
	}


	/**
	 * Get the associated Estado object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Estado The associated Estado object.
	 * @throws     PropelException
	 */
	public function getEstado(PropelPDO $con = null)
	{
		if ($this->aEstado === null && ($this->estado_id !== null)) {
			$c = new Criteria(EstadoPeer::DATABASE_NAME);
			$c->add(EstadoPeer::ID, $this->estado_id);
			$this->aEstado = EstadoPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aEstado->addUbicacions($this);
			 */
		}
		return $this->aEstado;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

			$this->aEmpresa = null;
			$this->aEstado = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseUbicacion:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseUbicacion::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseUbicacion
