<?php

/**
 * Base class that represents a row from the 'empresa' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Tue Nov 10 21:52:52 2009
 *
 * @package    lib.model.om
 */
abstract class BaseEmpresa extends BaseObject  implements Persistent {


  const PEER = 'EmpresaPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        EmpresaPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the user_id field.
	 * @var        int
	 */
	protected $user_id;

	/**
	 * The value for the nombre field.
	 * @var        string
	 */
	protected $nombre;

	/**
	 * The value for the descripcion field.
	 * @var        string
	 */
	protected $descripcion;

	/**
	 * The value for the afiliacion_fonacot field.
	 * @var        string
	 */
	protected $afiliacion_fonacot;

	/**
	 * The value for the slot field.
	 * @var        string
	 */
	protected $slot;

	/**
	 * @var        Perfil
	 */
	protected $aPerfil;

	/**
	 * @var        General one-to-one related General object
	 */
	protected $singleGeneral;

	/**
	 * @var        Ubicacion one-to-one related Ubicacion object
	 */
	protected $singleUbicacion;

	/**
	 * @var        array Producto[] Collection to store aggregation of Producto objects.
	 */
	protected $collProductos;

	/**
	 * @var        Criteria The criteria used to select the current contents of collProductos.
	 */
	private $lastProductoCriteria = null;

	/**
	 * @var        Tramite one-to-one related Tramite object
	 */
	protected $singleTramite;

	/**
	 * @var        Micrositio one-to-one related Micrositio object
	 */
	protected $singleMicrositio;

	/**
	 * @var        array EmpresaCategoria[] Collection to store aggregation of EmpresaCategoria objects.
	 */
	protected $collEmpresaCategorias;

	/**
	 * @var        Criteria The criteria used to select the current contents of collEmpresaCategorias.
	 */
	private $lastEmpresaCategoriaCriteria = null;

	/**
	 * @var        array EmpresaSegmento[] Collection to store aggregation of EmpresaSegmento objects.
	 */
	protected $collEmpresaSegmentos;

	/**
	 * @var        Criteria The criteria used to select the current contents of collEmpresaSegmentos.
	 */
	private $lastEmpresaSegmentoCriteria = null;

	/**
	 * @var        array Banner[] Collection to store aggregation of Banner objects.
	 */
	protected $collBanners;

	/**
	 * @var        Criteria The criteria used to select the current contents of collBanners.
	 */
	private $lastBannerCriteria = null;

	/**
	 * @var        array Cupon[] Collection to store aggregation of Cupon objects.
	 */
	protected $collCupons;

	/**
	 * @var        Criteria The criteria used to select the current contents of collCupons.
	 */
	private $lastCuponCriteria = null;

	/**
	 * @var        array Noticia[] Collection to store aggregation of Noticia objects.
	 */
	protected $collNoticias;

	/**
	 * @var        Criteria The criteria used to select the current contents of collNoticias.
	 */
	private $lastNoticiaCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseEmpresa object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [user_id] column value.
	 * 
	 * @return     int
	 */
	public function getUserId()
	{
		return $this->user_id;
	}

	/**
	 * Get the [nombre] column value.
	 * 
	 * @return     string
	 */
	public function getNombre()
	{
		return $this->nombre;
	}

	/**
	 * Get the [descripcion] column value.
	 * 
	 * @return     string
	 */
	public function getDescripcion()
	{
		return $this->descripcion;
	}

	/**
	 * Get the [afiliacion_fonacot] column value.
	 * 
	 * @return     string
	 */
	public function getAfiliacionFonacot()
	{
		return $this->afiliacion_fonacot;
	}

	/**
	 * Get the [slot] column value.
	 * 
	 * @return     string
	 */
	public function getSlot()
	{
		return $this->slot;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Empresa The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = EmpresaPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [user_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Empresa The current object (for fluent API support)
	 */
	public function setUserId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->user_id !== $v) {
			$this->user_id = $v;
			$this->modifiedColumns[] = EmpresaPeer::USER_ID;
		}

		if ($this->aPerfil !== null && $this->aPerfil->getUserId() !== $v) {
			$this->aPerfil = null;
		}

		return $this;
	} // setUserId()

	/**
	 * Set the value of [nombre] column.
	 * 
	 * @param      string $v new value
	 * @return     Empresa The current object (for fluent API support)
	 */
	public function setNombre($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->nombre !== $v) {
			$this->nombre = $v;
			$this->modifiedColumns[] = EmpresaPeer::NOMBRE;
		}

		return $this;
	} // setNombre()

	/**
	 * Set the value of [descripcion] column.
	 * 
	 * @param      string $v new value
	 * @return     Empresa The current object (for fluent API support)
	 */
	public function setDescripcion($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->descripcion !== $v) {
			$this->descripcion = $v;
			$this->modifiedColumns[] = EmpresaPeer::DESCRIPCION;
		}

		return $this;
	} // setDescripcion()

	/**
	 * Set the value of [afiliacion_fonacot] column.
	 * 
	 * @param      string $v new value
	 * @return     Empresa The current object (for fluent API support)
	 */
	public function setAfiliacionFonacot($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->afiliacion_fonacot !== $v) {
			$this->afiliacion_fonacot = $v;
			$this->modifiedColumns[] = EmpresaPeer::AFILIACION_FONACOT;
		}

		return $this;
	} // setAfiliacionFonacot()

	/**
	 * Set the value of [slot] column.
	 * 
	 * @param      string $v new value
	 * @return     Empresa The current object (for fluent API support)
	 */
	public function setSlot($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->slot !== $v) {
			$this->slot = $v;
			$this->modifiedColumns[] = EmpresaPeer::SLOT;
		}

		return $this;
	} // setSlot()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array())) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->user_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->nombre = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->descripcion = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->afiliacion_fonacot = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->slot = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 6; // 6 = EmpresaPeer::NUM_COLUMNS - EmpresaPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Empresa object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aPerfil !== null && $this->user_id !== $this->aPerfil->getUserId()) {
			$this->aPerfil = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(EmpresaPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = EmpresaPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aPerfil = null;
			$this->singleGeneral = null;

			$this->singleUbicacion = null;

			$this->collProductos = null;
			$this->lastProductoCriteria = null;

			$this->singleTramite = null;

			$this->singleMicrositio = null;

			$this->collEmpresaCategorias = null;
			$this->lastEmpresaCategoriaCriteria = null;

			$this->collEmpresaSegmentos = null;
			$this->lastEmpresaSegmentoCriteria = null;

			$this->collBanners = null;
			$this->lastBannerCriteria = null;

			$this->collCupons = null;
			$this->lastCuponCriteria = null;

			$this->collNoticias = null;
			$this->lastNoticiaCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseEmpresa:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(EmpresaPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			EmpresaPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseEmpresa:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseEmpresa:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(EmpresaPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseEmpresa:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			EmpresaPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aPerfil !== null) {
				if ($this->aPerfil->isModified() || $this->aPerfil->isNew()) {
					$affectedRows += $this->aPerfil->save($con);
				}
				$this->setPerfil($this->aPerfil);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = EmpresaPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = EmpresaPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += EmpresaPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->singleGeneral !== null) {
				if (!$this->singleGeneral->isDeleted()) {
						$affectedRows += $this->singleGeneral->save($con);
				}
			}

			if ($this->singleUbicacion !== null) {
				if (!$this->singleUbicacion->isDeleted()) {
						$affectedRows += $this->singleUbicacion->save($con);
				}
			}

			if ($this->collProductos !== null) {
				foreach ($this->collProductos as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->singleTramite !== null) {
				if (!$this->singleTramite->isDeleted()) {
						$affectedRows += $this->singleTramite->save($con);
				}
			}

			if ($this->singleMicrositio !== null) {
				if (!$this->singleMicrositio->isDeleted()) {
						$affectedRows += $this->singleMicrositio->save($con);
				}
			}

			if ($this->collEmpresaCategorias !== null) {
				foreach ($this->collEmpresaCategorias as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collEmpresaSegmentos !== null) {
				foreach ($this->collEmpresaSegmentos as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collBanners !== null) {
				foreach ($this->collBanners as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collCupons !== null) {
				foreach ($this->collCupons as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collNoticias !== null) {
				foreach ($this->collNoticias as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aPerfil !== null) {
				if (!$this->aPerfil->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aPerfil->getValidationFailures());
				}
			}


			if (($retval = EmpresaPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->singleGeneral !== null) {
					if (!$this->singleGeneral->validate($columns)) {
						$failureMap = array_merge($failureMap, $this->singleGeneral->getValidationFailures());
					}
				}

				if ($this->singleUbicacion !== null) {
					if (!$this->singleUbicacion->validate($columns)) {
						$failureMap = array_merge($failureMap, $this->singleUbicacion->getValidationFailures());
					}
				}

				if ($this->collProductos !== null) {
					foreach ($this->collProductos as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->singleTramite !== null) {
					if (!$this->singleTramite->validate($columns)) {
						$failureMap = array_merge($failureMap, $this->singleTramite->getValidationFailures());
					}
				}

				if ($this->singleMicrositio !== null) {
					if (!$this->singleMicrositio->validate($columns)) {
						$failureMap = array_merge($failureMap, $this->singleMicrositio->getValidationFailures());
					}
				}

				if ($this->collEmpresaCategorias !== null) {
					foreach ($this->collEmpresaCategorias as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collEmpresaSegmentos !== null) {
					foreach ($this->collEmpresaSegmentos as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collBanners !== null) {
					foreach ($this->collBanners as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collCupons !== null) {
					foreach ($this->collCupons as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collNoticias !== null) {
					foreach ($this->collNoticias as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = EmpresaPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getUserId();
				break;
			case 2:
				return $this->getNombre();
				break;
			case 3:
				return $this->getDescripcion();
				break;
			case 4:
				return $this->getAfiliacionFonacot();
				break;
			case 5:
				return $this->getSlot();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = EmpresaPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getUserId(),
			$keys[2] => $this->getNombre(),
			$keys[3] => $this->getDescripcion(),
			$keys[4] => $this->getAfiliacionFonacot(),
			$keys[5] => $this->getSlot(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = EmpresaPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setUserId($value);
				break;
			case 2:
				$this->setNombre($value);
				break;
			case 3:
				$this->setDescripcion($value);
				break;
			case 4:
				$this->setAfiliacionFonacot($value);
				break;
			case 5:
				$this->setSlot($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = EmpresaPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setUserId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setNombre($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setDescripcion($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setAfiliacionFonacot($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setSlot($arr[$keys[5]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(EmpresaPeer::DATABASE_NAME);

		if ($this->isColumnModified(EmpresaPeer::ID)) $criteria->add(EmpresaPeer::ID, $this->id);
		if ($this->isColumnModified(EmpresaPeer::USER_ID)) $criteria->add(EmpresaPeer::USER_ID, $this->user_id);
		if ($this->isColumnModified(EmpresaPeer::NOMBRE)) $criteria->add(EmpresaPeer::NOMBRE, $this->nombre);
		if ($this->isColumnModified(EmpresaPeer::DESCRIPCION)) $criteria->add(EmpresaPeer::DESCRIPCION, $this->descripcion);
		if ($this->isColumnModified(EmpresaPeer::AFILIACION_FONACOT)) $criteria->add(EmpresaPeer::AFILIACION_FONACOT, $this->afiliacion_fonacot);
		if ($this->isColumnModified(EmpresaPeer::SLOT)) $criteria->add(EmpresaPeer::SLOT, $this->slot);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(EmpresaPeer::DATABASE_NAME);

		$criteria->add(EmpresaPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Empresa (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setUserId($this->user_id);

		$copyObj->setNombre($this->nombre);

		$copyObj->setDescripcion($this->descripcion);

		$copyObj->setAfiliacionFonacot($this->afiliacion_fonacot);

		$copyObj->setSlot($this->slot);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			$relObj = $this->getGeneral();
			if ($relObj) {
				$copyObj->setGeneral($relObj->copy($deepCopy));
			}

			$relObj = $this->getUbicacion();
			if ($relObj) {
				$copyObj->setUbicacion($relObj->copy($deepCopy));
			}

			foreach ($this->getProductos() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addProducto($relObj->copy($deepCopy));
				}
			}

			$relObj = $this->getTramite();
			if ($relObj) {
				$copyObj->setTramite($relObj->copy($deepCopy));
			}

			$relObj = $this->getMicrositio();
			if ($relObj) {
				$copyObj->setMicrositio($relObj->copy($deepCopy));
			}

			foreach ($this->getEmpresaCategorias() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addEmpresaCategoria($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getEmpresaSegmentos() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addEmpresaSegmento($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getBanners() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addBanner($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getCupons() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addCupon($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getNoticias() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addNoticia($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Empresa Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     EmpresaPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new EmpresaPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Perfil object.
	 *
	 * @param      Perfil $v
	 * @return     Empresa The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setPerfil(Perfil $v = null)
	{
		if ($v === null) {
			$this->setUserId(NULL);
		} else {
			$this->setUserId($v->getUserId());
		}

		$this->aPerfil = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Perfil object, it will not be re-added.
		if ($v !== null) {
			$v->addEmpresa($this);
		}

		return $this;
	}


	/**
	 * Get the associated Perfil object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Perfil The associated Perfil object.
	 * @throws     PropelException
	 */
	public function getPerfil(PropelPDO $con = null)
	{
		if ($this->aPerfil === null && ($this->user_id !== null)) {
			$c = new Criteria(PerfilPeer::DATABASE_NAME);
			$c->add(PerfilPeer::USER_ID, $this->user_id);
			$this->aPerfil = PerfilPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aPerfil->addEmpresas($this);
			 */
		}
		return $this->aPerfil;
	}

	/**
	 * Gets a single General object, which is related to this object by a one-to-one relationship.
	 *
	 * @param      PropelPDO $con
	 * @return     General
	 * @throws     PropelException
	 */
	public function getGeneral(PropelPDO $con = null)
	{

		if ($this->singleGeneral === null && !$this->isNew()) {
			$this->singleGeneral = GeneralPeer::retrieveByPK($this->id, $con);
		}

		return $this->singleGeneral;
	}

	/**
	 * Sets a single General object as related to this object by a one-to-one relationship.
	 *
	 * @param      General $l General
	 * @return     Empresa The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setGeneral(General $v)
	{
		$this->singleGeneral = $v;

		// Make sure that that the passed-in General isn't already associated with this object
		if ($v->getEmpresa() === null) {
			$v->setEmpresa($this);
		}

		return $this;
	}

	/**
	 * Gets a single Ubicacion object, which is related to this object by a one-to-one relationship.
	 *
	 * @param      PropelPDO $con
	 * @return     Ubicacion
	 * @throws     PropelException
	 */
	public function getUbicacion(PropelPDO $con = null)
	{

		if ($this->singleUbicacion === null && !$this->isNew()) {
			$this->singleUbicacion = UbicacionPeer::retrieveByPK($this->id, $con);
		}

		return $this->singleUbicacion;
	}

	/**
	 * Sets a single Ubicacion object as related to this object by a one-to-one relationship.
	 *
	 * @param      Ubicacion $l Ubicacion
	 * @return     Empresa The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setUbicacion(Ubicacion $v)
	{
		$this->singleUbicacion = $v;

		// Make sure that that the passed-in Ubicacion isn't already associated with this object
		if ($v->getEmpresa() === null) {
			$v->setEmpresa($this);
		}

		return $this;
	}

	/**
	 * Clears out the collProductos collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addProductos()
	 */
	public function clearProductos()
	{
		$this->collProductos = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collProductos collection (array).
	 *
	 * By default this just sets the collProductos collection to an empty array (like clearcollProductos());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initProductos()
	{
		$this->collProductos = array();
	}

	/**
	 * Gets an array of Producto objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Empresa has previously been saved, it will retrieve
	 * related Productos from storage. If this Empresa is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Producto[]
	 * @throws     PropelException
	 */
	public function getProductos($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EmpresaPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collProductos === null) {
			if ($this->isNew()) {
			   $this->collProductos = array();
			} else {

				$criteria->add(ProductoPeer::EMPRESA_ID, $this->id);

				ProductoPeer::addSelectColumns($criteria);
				$this->collProductos = ProductoPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(ProductoPeer::EMPRESA_ID, $this->id);

				ProductoPeer::addSelectColumns($criteria);
				if (!isset($this->lastProductoCriteria) || !$this->lastProductoCriteria->equals($criteria)) {
					$this->collProductos = ProductoPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastProductoCriteria = $criteria;
		return $this->collProductos;
	}

	/**
	 * Returns the number of related Producto objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Producto objects.
	 * @throws     PropelException
	 */
	public function countProductos(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EmpresaPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collProductos === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(ProductoPeer::EMPRESA_ID, $this->id);

				$count = ProductoPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(ProductoPeer::EMPRESA_ID, $this->id);

				if (!isset($this->lastProductoCriteria) || !$this->lastProductoCriteria->equals($criteria)) {
					$count = ProductoPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collProductos);
				}
			} else {
				$count = count($this->collProductos);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Producto object to this object
	 * through the Producto foreign key attribute.
	 *
	 * @param      Producto $l Producto
	 * @return     void
	 * @throws     PropelException
	 */
	public function addProducto(Producto $l)
	{
		if ($this->collProductos === null) {
			$this->initProductos();
		}
		if (!in_array($l, $this->collProductos, true)) { // only add it if the **same** object is not already associated
			array_push($this->collProductos, $l);
			$l->setEmpresa($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Empresa is new, it will return
	 * an empty collection; or if this Empresa has previously
	 * been saved, it will retrieve related Productos from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Empresa.
	 */
	public function getProductosJoinCategoria($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EmpresaPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collProductos === null) {
			if ($this->isNew()) {
				$this->collProductos = array();
			} else {

				$criteria->add(ProductoPeer::EMPRESA_ID, $this->id);

				$this->collProductos = ProductoPeer::doSelectJoinCategoria($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(ProductoPeer::EMPRESA_ID, $this->id);

			if (!isset($this->lastProductoCriteria) || !$this->lastProductoCriteria->equals($criteria)) {
				$this->collProductos = ProductoPeer::doSelectJoinCategoria($criteria, $con, $join_behavior);
			}
		}
		$this->lastProductoCriteria = $criteria;

		return $this->collProductos;
	}

	/**
	 * Gets a single Tramite object, which is related to this object by a one-to-one relationship.
	 *
	 * @param      PropelPDO $con
	 * @return     Tramite
	 * @throws     PropelException
	 */
	public function getTramite(PropelPDO $con = null)
	{

		if ($this->singleTramite === null && !$this->isNew()) {
			$this->singleTramite = TramitePeer::retrieveByPK($this->id, $con);
		}

		return $this->singleTramite;
	}

	/**
	 * Sets a single Tramite object as related to this object by a one-to-one relationship.
	 *
	 * @param      Tramite $l Tramite
	 * @return     Empresa The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setTramite(Tramite $v)
	{
		$this->singleTramite = $v;

		// Make sure that that the passed-in Tramite isn't already associated with this object
		if ($v->getEmpresa() === null) {
			$v->setEmpresa($this);
		}

		return $this;
	}

	/**
	 * Gets a single Micrositio object, which is related to this object by a one-to-one relationship.
	 *
	 * @param      PropelPDO $con
	 * @return     Micrositio
	 * @throws     PropelException
	 */
	public function getMicrositio(PropelPDO $con = null)
	{

		if ($this->singleMicrositio === null && !$this->isNew()) {
			$this->singleMicrositio = MicrositioPeer::retrieveByPK($this->id, $con);
		}

		return $this->singleMicrositio;
	}

	/**
	 * Sets a single Micrositio object as related to this object by a one-to-one relationship.
	 *
	 * @param      Micrositio $l Micrositio
	 * @return     Empresa The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setMicrositio(Micrositio $v)
	{
		$this->singleMicrositio = $v;

		// Make sure that that the passed-in Micrositio isn't already associated with this object
		if ($v->getEmpresa() === null) {
			$v->setEmpresa($this);
		}

		return $this;
	}

	/**
	 * Clears out the collEmpresaCategorias collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addEmpresaCategorias()
	 */
	public function clearEmpresaCategorias()
	{
		$this->collEmpresaCategorias = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collEmpresaCategorias collection (array).
	 *
	 * By default this just sets the collEmpresaCategorias collection to an empty array (like clearcollEmpresaCategorias());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initEmpresaCategorias()
	{
		$this->collEmpresaCategorias = array();
	}

	/**
	 * Gets an array of EmpresaCategoria objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Empresa has previously been saved, it will retrieve
	 * related EmpresaCategorias from storage. If this Empresa is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array EmpresaCategoria[]
	 * @throws     PropelException
	 */
	public function getEmpresaCategorias($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EmpresaPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collEmpresaCategorias === null) {
			if ($this->isNew()) {
			   $this->collEmpresaCategorias = array();
			} else {

				$criteria->add(EmpresaCategoriaPeer::EMPRESA_ID, $this->id);

				EmpresaCategoriaPeer::addSelectColumns($criteria);
				$this->collEmpresaCategorias = EmpresaCategoriaPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(EmpresaCategoriaPeer::EMPRESA_ID, $this->id);

				EmpresaCategoriaPeer::addSelectColumns($criteria);
				if (!isset($this->lastEmpresaCategoriaCriteria) || !$this->lastEmpresaCategoriaCriteria->equals($criteria)) {
					$this->collEmpresaCategorias = EmpresaCategoriaPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastEmpresaCategoriaCriteria = $criteria;
		return $this->collEmpresaCategorias;
	}

	/**
	 * Returns the number of related EmpresaCategoria objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related EmpresaCategoria objects.
	 * @throws     PropelException
	 */
	public function countEmpresaCategorias(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EmpresaPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collEmpresaCategorias === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(EmpresaCategoriaPeer::EMPRESA_ID, $this->id);

				$count = EmpresaCategoriaPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(EmpresaCategoriaPeer::EMPRESA_ID, $this->id);

				if (!isset($this->lastEmpresaCategoriaCriteria) || !$this->lastEmpresaCategoriaCriteria->equals($criteria)) {
					$count = EmpresaCategoriaPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collEmpresaCategorias);
				}
			} else {
				$count = count($this->collEmpresaCategorias);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a EmpresaCategoria object to this object
	 * through the EmpresaCategoria foreign key attribute.
	 *
	 * @param      EmpresaCategoria $l EmpresaCategoria
	 * @return     void
	 * @throws     PropelException
	 */
	public function addEmpresaCategoria(EmpresaCategoria $l)
	{
		if ($this->collEmpresaCategorias === null) {
			$this->initEmpresaCategorias();
		}
		if (!in_array($l, $this->collEmpresaCategorias, true)) { // only add it if the **same** object is not already associated
			array_push($this->collEmpresaCategorias, $l);
			$l->setEmpresa($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Empresa is new, it will return
	 * an empty collection; or if this Empresa has previously
	 * been saved, it will retrieve related EmpresaCategorias from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Empresa.
	 */
	public function getEmpresaCategoriasJoinCategoria($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EmpresaPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collEmpresaCategorias === null) {
			if ($this->isNew()) {
				$this->collEmpresaCategorias = array();
			} else {

				$criteria->add(EmpresaCategoriaPeer::EMPRESA_ID, $this->id);

				$this->collEmpresaCategorias = EmpresaCategoriaPeer::doSelectJoinCategoria($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(EmpresaCategoriaPeer::EMPRESA_ID, $this->id);

			if (!isset($this->lastEmpresaCategoriaCriteria) || !$this->lastEmpresaCategoriaCriteria->equals($criteria)) {
				$this->collEmpresaCategorias = EmpresaCategoriaPeer::doSelectJoinCategoria($criteria, $con, $join_behavior);
			}
		}
		$this->lastEmpresaCategoriaCriteria = $criteria;

		return $this->collEmpresaCategorias;
	}

	/**
	 * Clears out the collEmpresaSegmentos collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addEmpresaSegmentos()
	 */
	public function clearEmpresaSegmentos()
	{
		$this->collEmpresaSegmentos = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collEmpresaSegmentos collection (array).
	 *
	 * By default this just sets the collEmpresaSegmentos collection to an empty array (like clearcollEmpresaSegmentos());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initEmpresaSegmentos()
	{
		$this->collEmpresaSegmentos = array();
	}

	/**
	 * Gets an array of EmpresaSegmento objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Empresa has previously been saved, it will retrieve
	 * related EmpresaSegmentos from storage. If this Empresa is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array EmpresaSegmento[]
	 * @throws     PropelException
	 */
	public function getEmpresaSegmentos($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EmpresaPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collEmpresaSegmentos === null) {
			if ($this->isNew()) {
			   $this->collEmpresaSegmentos = array();
			} else {

				$criteria->add(EmpresaSegmentoPeer::EMPRESA_ID, $this->id);

				EmpresaSegmentoPeer::addSelectColumns($criteria);
				$this->collEmpresaSegmentos = EmpresaSegmentoPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(EmpresaSegmentoPeer::EMPRESA_ID, $this->id);

				EmpresaSegmentoPeer::addSelectColumns($criteria);
				if (!isset($this->lastEmpresaSegmentoCriteria) || !$this->lastEmpresaSegmentoCriteria->equals($criteria)) {
					$this->collEmpresaSegmentos = EmpresaSegmentoPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastEmpresaSegmentoCriteria = $criteria;
		return $this->collEmpresaSegmentos;
	}

	/**
	 * Returns the number of related EmpresaSegmento objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related EmpresaSegmento objects.
	 * @throws     PropelException
	 */
	public function countEmpresaSegmentos(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EmpresaPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collEmpresaSegmentos === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(EmpresaSegmentoPeer::EMPRESA_ID, $this->id);

				$count = EmpresaSegmentoPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(EmpresaSegmentoPeer::EMPRESA_ID, $this->id);

				if (!isset($this->lastEmpresaSegmentoCriteria) || !$this->lastEmpresaSegmentoCriteria->equals($criteria)) {
					$count = EmpresaSegmentoPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collEmpresaSegmentos);
				}
			} else {
				$count = count($this->collEmpresaSegmentos);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a EmpresaSegmento object to this object
	 * through the EmpresaSegmento foreign key attribute.
	 *
	 * @param      EmpresaSegmento $l EmpresaSegmento
	 * @return     void
	 * @throws     PropelException
	 */
	public function addEmpresaSegmento(EmpresaSegmento $l)
	{
		if ($this->collEmpresaSegmentos === null) {
			$this->initEmpresaSegmentos();
		}
		if (!in_array($l, $this->collEmpresaSegmentos, true)) { // only add it if the **same** object is not already associated
			array_push($this->collEmpresaSegmentos, $l);
			$l->setEmpresa($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Empresa is new, it will return
	 * an empty collection; or if this Empresa has previously
	 * been saved, it will retrieve related EmpresaSegmentos from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Empresa.
	 */
	public function getEmpresaSegmentosJoinSegmento($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EmpresaPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collEmpresaSegmentos === null) {
			if ($this->isNew()) {
				$this->collEmpresaSegmentos = array();
			} else {

				$criteria->add(EmpresaSegmentoPeer::EMPRESA_ID, $this->id);

				$this->collEmpresaSegmentos = EmpresaSegmentoPeer::doSelectJoinSegmento($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(EmpresaSegmentoPeer::EMPRESA_ID, $this->id);

			if (!isset($this->lastEmpresaSegmentoCriteria) || !$this->lastEmpresaSegmentoCriteria->equals($criteria)) {
				$this->collEmpresaSegmentos = EmpresaSegmentoPeer::doSelectJoinSegmento($criteria, $con, $join_behavior);
			}
		}
		$this->lastEmpresaSegmentoCriteria = $criteria;

		return $this->collEmpresaSegmentos;
	}

	/**
	 * Clears out the collBanners collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addBanners()
	 */
	public function clearBanners()
	{
		$this->collBanners = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collBanners collection (array).
	 *
	 * By default this just sets the collBanners collection to an empty array (like clearcollBanners());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initBanners()
	{
		$this->collBanners = array();
	}

	/**
	 * Gets an array of Banner objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Empresa has previously been saved, it will retrieve
	 * related Banners from storage. If this Empresa is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Banner[]
	 * @throws     PropelException
	 */
	public function getBanners($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EmpresaPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collBanners === null) {
			if ($this->isNew()) {
			   $this->collBanners = array();
			} else {

				$criteria->add(BannerPeer::EMPRESA_ID, $this->id);

				BannerPeer::addSelectColumns($criteria);
				$this->collBanners = BannerPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(BannerPeer::EMPRESA_ID, $this->id);

				BannerPeer::addSelectColumns($criteria);
				if (!isset($this->lastBannerCriteria) || !$this->lastBannerCriteria->equals($criteria)) {
					$this->collBanners = BannerPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastBannerCriteria = $criteria;
		return $this->collBanners;
	}

	/**
	 * Returns the number of related Banner objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Banner objects.
	 * @throws     PropelException
	 */
	public function countBanners(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EmpresaPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collBanners === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(BannerPeer::EMPRESA_ID, $this->id);

				$count = BannerPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(BannerPeer::EMPRESA_ID, $this->id);

				if (!isset($this->lastBannerCriteria) || !$this->lastBannerCriteria->equals($criteria)) {
					$count = BannerPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collBanners);
				}
			} else {
				$count = count($this->collBanners);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Banner object to this object
	 * through the Banner foreign key attribute.
	 *
	 * @param      Banner $l Banner
	 * @return     void
	 * @throws     PropelException
	 */
	public function addBanner(Banner $l)
	{
		if ($this->collBanners === null) {
			$this->initBanners();
		}
		if (!in_array($l, $this->collBanners, true)) { // only add it if the **same** object is not already associated
			array_push($this->collBanners, $l);
			$l->setEmpresa($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Empresa is new, it will return
	 * an empty collection; or if this Empresa has previously
	 * been saved, it will retrieve related Banners from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Empresa.
	 */
	public function getBannersJoinSegmento($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EmpresaPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collBanners === null) {
			if ($this->isNew()) {
				$this->collBanners = array();
			} else {

				$criteria->add(BannerPeer::EMPRESA_ID, $this->id);

				$this->collBanners = BannerPeer::doSelectJoinSegmento($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(BannerPeer::EMPRESA_ID, $this->id);

			if (!isset($this->lastBannerCriteria) || !$this->lastBannerCriteria->equals($criteria)) {
				$this->collBanners = BannerPeer::doSelectJoinSegmento($criteria, $con, $join_behavior);
			}
		}
		$this->lastBannerCriteria = $criteria;

		return $this->collBanners;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Empresa is new, it will return
	 * an empty collection; or if this Empresa has previously
	 * been saved, it will retrieve related Banners from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Empresa.
	 */
	public function getBannersJoinCategoria($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EmpresaPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collBanners === null) {
			if ($this->isNew()) {
				$this->collBanners = array();
			} else {

				$criteria->add(BannerPeer::EMPRESA_ID, $this->id);

				$this->collBanners = BannerPeer::doSelectJoinCategoria($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(BannerPeer::EMPRESA_ID, $this->id);

			if (!isset($this->lastBannerCriteria) || !$this->lastBannerCriteria->equals($criteria)) {
				$this->collBanners = BannerPeer::doSelectJoinCategoria($criteria, $con, $join_behavior);
			}
		}
		$this->lastBannerCriteria = $criteria;

		return $this->collBanners;
	}

	/**
	 * Clears out the collCupons collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addCupons()
	 */
	public function clearCupons()
	{
		$this->collCupons = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collCupons collection (array).
	 *
	 * By default this just sets the collCupons collection to an empty array (like clearcollCupons());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initCupons()
	{
		$this->collCupons = array();
	}

	/**
	 * Gets an array of Cupon objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Empresa has previously been saved, it will retrieve
	 * related Cupons from storage. If this Empresa is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Cupon[]
	 * @throws     PropelException
	 */
	public function getCupons($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EmpresaPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collCupons === null) {
			if ($this->isNew()) {
			   $this->collCupons = array();
			} else {

				$criteria->add(CuponPeer::EMPRESA_ID, $this->id);

				CuponPeer::addSelectColumns($criteria);
				$this->collCupons = CuponPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(CuponPeer::EMPRESA_ID, $this->id);

				CuponPeer::addSelectColumns($criteria);
				if (!isset($this->lastCuponCriteria) || !$this->lastCuponCriteria->equals($criteria)) {
					$this->collCupons = CuponPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastCuponCriteria = $criteria;
		return $this->collCupons;
	}

	/**
	 * Returns the number of related Cupon objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Cupon objects.
	 * @throws     PropelException
	 */
	public function countCupons(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EmpresaPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collCupons === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(CuponPeer::EMPRESA_ID, $this->id);

				$count = CuponPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(CuponPeer::EMPRESA_ID, $this->id);

				if (!isset($this->lastCuponCriteria) || !$this->lastCuponCriteria->equals($criteria)) {
					$count = CuponPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collCupons);
				}
			} else {
				$count = count($this->collCupons);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Cupon object to this object
	 * through the Cupon foreign key attribute.
	 *
	 * @param      Cupon $l Cupon
	 * @return     void
	 * @throws     PropelException
	 */
	public function addCupon(Cupon $l)
	{
		if ($this->collCupons === null) {
			$this->initCupons();
		}
		if (!in_array($l, $this->collCupons, true)) { // only add it if the **same** object is not already associated
			array_push($this->collCupons, $l);
			$l->setEmpresa($this);
		}
	}

	/**
	 * Clears out the collNoticias collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addNoticias()
	 */
	public function clearNoticias()
	{
		$this->collNoticias = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collNoticias collection (array).
	 *
	 * By default this just sets the collNoticias collection to an empty array (like clearcollNoticias());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initNoticias()
	{
		$this->collNoticias = array();
	}

	/**
	 * Gets an array of Noticia objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Empresa has previously been saved, it will retrieve
	 * related Noticias from storage. If this Empresa is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Noticia[]
	 * @throws     PropelException
	 */
	public function getNoticias($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EmpresaPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collNoticias === null) {
			if ($this->isNew()) {
			   $this->collNoticias = array();
			} else {

				$criteria->add(NoticiaPeer::EMPRESA_ID, $this->id);

				NoticiaPeer::addSelectColumns($criteria);
				$this->collNoticias = NoticiaPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(NoticiaPeer::EMPRESA_ID, $this->id);

				NoticiaPeer::addSelectColumns($criteria);
				if (!isset($this->lastNoticiaCriteria) || !$this->lastNoticiaCriteria->equals($criteria)) {
					$this->collNoticias = NoticiaPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastNoticiaCriteria = $criteria;
		return $this->collNoticias;
	}

	/**
	 * Returns the number of related Noticia objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Noticia objects.
	 * @throws     PropelException
	 */
	public function countNoticias(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(EmpresaPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collNoticias === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(NoticiaPeer::EMPRESA_ID, $this->id);

				$count = NoticiaPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(NoticiaPeer::EMPRESA_ID, $this->id);

				if (!isset($this->lastNoticiaCriteria) || !$this->lastNoticiaCriteria->equals($criteria)) {
					$count = NoticiaPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collNoticias);
				}
			} else {
				$count = count($this->collNoticias);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Noticia object to this object
	 * through the Noticia foreign key attribute.
	 *
	 * @param      Noticia $l Noticia
	 * @return     void
	 * @throws     PropelException
	 */
	public function addNoticia(Noticia $l)
	{
		if ($this->collNoticias === null) {
			$this->initNoticias();
		}
		if (!in_array($l, $this->collNoticias, true)) { // only add it if the **same** object is not already associated
			array_push($this->collNoticias, $l);
			$l->setEmpresa($this);
		}
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->singleGeneral) {
				$this->singleGeneral->clearAllReferences($deep);
			}
			if ($this->singleUbicacion) {
				$this->singleUbicacion->clearAllReferences($deep);
			}
			if ($this->collProductos) {
				foreach ((array) $this->collProductos as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->singleTramite) {
				$this->singleTramite->clearAllReferences($deep);
			}
			if ($this->singleMicrositio) {
				$this->singleMicrositio->clearAllReferences($deep);
			}
			if ($this->collEmpresaCategorias) {
				foreach ((array) $this->collEmpresaCategorias as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collEmpresaSegmentos) {
				foreach ((array) $this->collEmpresaSegmentos as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collBanners) {
				foreach ((array) $this->collBanners as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collCupons) {
				foreach ((array) $this->collCupons as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collNoticias) {
				foreach ((array) $this->collNoticias as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->singleGeneral = null;
		$this->singleUbicacion = null;
		$this->collProductos = null;
		$this->singleTramite = null;
		$this->singleMicrositio = null;
		$this->collEmpresaCategorias = null;
		$this->collEmpresaSegmentos = null;
		$this->collBanners = null;
		$this->collCupons = null;
		$this->collNoticias = null;
			$this->aPerfil = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseEmpresa:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseEmpresa::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseEmpresa
