generator:
  class: sfPropelGenerator
  param:
    model_class:           Empresa
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          empresa
    with_propel_route:     1
    css:                   generator.css

    config:
      actions:
        _save:            { label: Guardar }
        _save_and_add:    { label: Guardar y agregar otro }
        _delete:          { label: Borrar }
        _new:             { label: Nuevo }
        _edit:            { label: Editar }
        _list:            { label: Regresar }     
      fields:  ~
      list:    
        title:            Administación de Empresas
        actions:          []
        display:          [ id, nombre, afiliacion_fonacot ]
        object_actions:
          _edit:          ~
          _delete:        ~
          micrositio:     { label: Micrositio, action: editMicrositio }
          general:        { label: General, action: editGeneral }
          productos:      { label: Productos, action: verProductos }
          noticias:       { label: Noticias, action: verNoticias }
          ubicacion:      { label: Ubicación, action: editUbicacion }
          anuncios:       { label: Anuncios, action: verAnuncios }
          basico:         { label: Basico, action: cambiarBasico }
          intermedio:     { label: Intermedio, action: cambiarIntermedio }
          avanzado:       { label: Avanzado, action: cambiarAvanzado }          

      filter:  
        display:          [ nombre, afiliacion_fonacot]
      form:    ~
      edit:    
        title:            Editar Información
      new:   
        title:            Nueva Empresa
