generator:
  class: sfPropelGenerator
  param:
    model_class:           Noticia
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          noticia
    with_propel_route:     1
    css:                   generator.css

    config:
      actions: 
        _save:             { label: Guardar }
        _save_and_add:     { label: Guardar y agregar otro }
        _delete:           { label: Borrar }
        _new:              { label: Nuevo }
        _edit:             { label: Editar }
        _list:             { label: Regresar }
      fields:  ~
      list:   
        title:             Administración de Noticias
        peer_method:       doSelectJoinAll
        display:           [ empresa, titulo, fecha_publicacion ]
        actions:           {}
        object_actions:
          _edit:           ~
          _delete:         ~
          ver:             { label: Ver, action: view }
      filter: 
        display:           [ empresa_id, titulo, fecha_publicacion ]
      form:    ~
      edit:    
        title:             Editar Noticia
      new:    
        title:             Nueva Noticia
