indexSuccess:
  metas: 
    title:       <?php echo sfConfig::get('app_page_title')?> - Ubicaciones
    description:  Listado de las direcciones de las empresas

showSuccess:
  javascripts: [ http://maps.google.com/maps?file=api&v=2&key=<?php echo sfConfig::get('app_maps_api_key')?> ]
