all:
  maps:
    # API KEY LOCALHOST
    #api_key: ABQIAAAATJaLkLT575V_ip_KPJNmshT2yXp_ZAY8_ufC3CFXhHIE1NvwkxTD2fyI3-yB4ZhvWZDUfAVtJ8p7_w
    # API KEY Produccion
    api_key: ABQIAAAATJaLkLT575V_ip_KPJNmshSaNLPq6pceM9vpoL2ukfrLHGiXOhSVHX7Ey__LRTktreA9hhAaeJwsfw 
  upload_dir:             /uploads  
  upload_mini_dir:        /uploads/mini
  banner:
    width:                280
    height:               200
  sf_guard_plugin:
    profile_class:        Perfil
    profile_field_name:   user_id
    success_signin_url:   home/inicio
    success_signout_url:  home/index
  